{% set version = "0.4.4" %}

package:
  name: vincent
  version: {{ version }}

source:
  fn: vincent-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vincent/vincent-{{ version }}.tar.gz
  sha256: 5765bcd360140d2304e52728ad1d4382f3f919ea259a13932828680f2d84fcd3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - pandas

test:
  imports:
    - vincent

about:
  home: https://github.com/wrobstory/vincent
  license: MIT
  summary: 'A Python to Vega translator.'

extra:
  recipe-maintainers:
    - ocefpaf
